# Generated by Django 4.2.7 on 2023-12-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeditem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
